---
- name: Auto IP Assignment and Custom Backup
  hosts: routers
  gather_facts: no
  serial: 1

  tasks:
    
    - name: Configure Loopback with Dynamic IP
      cisco.ios.ios_config:
        lines:
          - description Ansible_Automation
          - "ip address {{ new_ip }} 255.255.255.0"
        parents: interface Loopback99

    
    - name: Save Running Config to Startup
      cisco.ios.ios_command:
        commands: write memory

    

    
    - name: Fetch Running Configuration
      cisco.ios.ios_command:
        commands: show running-config
      register: router_config  

    
    - name: Save Config to Local File
      copy:
        content: "{{ router_config.stdout[0] }}"
        dest: "./backups/{{ inventory_hostname }}_config.txt"
      delegate_to: localhost  
